'use client';

import { useState } from 'react';
import type { FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { medusa } from '@/lib/medusa';
import { StoreCreateCustomer } from '@medusajs/types';
import { useCustomer } from '@/app/providers/customerProvider';
import { useLocale } from '@/components/LocaleProvider';
import './register.css';

export default function RegisterPage() {
  const router = useRouter(); const { refreshCustomer } = useCustomer(); const { locale } = useLocale(); const fa = locale === 'fa';
  const [firstName, setFirstName] = useState(''); const [lastName, setLastName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(null); try { const result = await medusa.auth.register('customer', 'emailpass', { email, password }); if (typeof result !== 'string') { setError(fa ? 'پرونده شما قبل از ورود نیاز به تأیید دارد.' : 'YOUR DEAD FILE NEEDS VERIFICATION BEFORE YOU CAN ENTER.'); return; } await medusa.store.customer.create({ email, first_name: firstName, last_name: lastName }, {}, { Authorization: `Bearer ${result}` }); await medusa.auth.login('customer', 'emailpass', { email, password }); await refreshCustomer(); router.push(`/${locale}/account`); router.refresh(); } catch (err) { console.error('Registration failed:', err); setError(fa ? 'ساخت پرونده ممکن نشد. اطلاعات را بررسی و دوباره تلاش کنید.' : 'COULD NOT CREATE YOUR DEAD FILE. CHECK YOUR DETAILS AND TRY AGAIN.'); } finally { setLoading(false); } }
  return <div className="register-page"><section className="register-hero"><div className="register-kicker"><span>DEADSAINT // {fa ? 'مشتری جدید' : 'NEW CUSTOMER'}</span><span>{fa ? 'پروتکل ساخت پرونده' : 'FILE CREATION PROTOCOL'}</span></div><div className="register-title-row"><div><p className="register-eyebrow">THE DEAD FILE</p><h1>{fa ? <>پیوستن<br />به<br />مرده‌ها.</> : <>JOIN<br />THE<br />DEAD.</>}</h1></div><div className="register-stamp"><span>STATUS</span><strong>UNBURIED</strong></div></div></section>
    <section className="register-form-section"><div className="register-copy"><span className="register-section-index">01 /</span><h2>{fa ? <>پرونده<br />خودت را بساز.</> : <>CREATE<br />YOUR FILE.</>}</h2><p>{fa ? 'حساب ددسینت سفارش‌ها، اطلاعات و آدرس‌هایت را یک‌جا نگه می‌دارد. یک رمز انتخاب کن و رسماً ثبت شو.' : 'Your DeadSaint account keeps your orders, details, and addresses in one place. Pick a password and get yourself officially documented.'}</p></div>
      <form className="register-form" onSubmit={handleSubmit}><div className="register-name-grid"><label><span>{fa ? 'نام' : 'FIRST NAME'}</span><input type="text" name="firstName" value={firstName} onChange={e => setFirstName(e.target.value)} autoComplete="given-name" required /></label><label><span>{fa ? 'نام خانوادگی' : 'LAST NAME'}</span><input type="text" name="lastName" value={lastName} onChange={e => setLastName(e.target.value)} autoComplete="family-name" required /></label></div><label><span>{fa ? 'ایمیل' : 'EMAIL ADDRESS'}</span><input type="email" name="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@deadsaint.com" autoComplete="email" required /></label><label><span>{fa ? 'رمز عبور' : 'PASSWORD'}</span><input type="password" name="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="8+ characters" autoComplete="new-password" minLength={8} required /></label>{error && <p className="register-error">☠ {error}</p>}<button type="submit" className="register-submit" disabled={loading}>{loading ? (fa ? 'در حال ساخت پرونده...' : 'CREATING FILE...') : (fa ? 'ساخت پرونده من ↗' : 'CREATE MY DEAD FILE ↗')}</button><div className="register-divider"><span /><small>{fa ? 'از قبل یکی از ما هستی؟' : 'ALREADY ONE OF US?'}</small><span /></div><Link href={`/${locale}/login`} className="register-login">{fa ? 'بازگشت به ورود ↗' : 'RETURN TO LOGIN ↗'}</Link></form></section><footer className="register-footer"><span>FILE CREATION LOGGED // DEADSAINT HQ</span><strong>☠ NO LIVING MEMBERS REQUIRED ☠</strong></footer></div>;
}
